baseURL = "https://mobius-group.github.io"
title = "Möbius Group"
languageCode = "en"
DefaultContentLanguage = "en" # Change this to change the site's language
theme = "hugo.386"
preserveTaxonomyNames = true

[params]
    # The name to display as main title in the home page
    mainpagetitle = "Möbius Group"

    # The subtitle to display under the title in the home page
    mainpagesubtitle = "Welcome to the most clueless academic community in the universe" 

    # The description of your website. It will be displayed in the home page
    mainpagedesc = ""

    # The name to display in the copyright section in the footer
    copyrightname = "Möbius Group"

    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    copyrighturl = "https://github.com/Mobius-Group"

    # Show the "built on Hugo" disclaimer
    showhugo = true

    # Urls for social networks
    twitter = "https://twitter.com"
    github = "https://github.com"

    # Enables or disables the loading animations. false activates them. Default is false.
    loadfastload = false

    # Sets the speed for the page loading effect. Default is 1.0.
    loadspeedfactor = 1.0

    # Enables or disables the second flyby cursor. Default is false.
    loadonepass = false

[params.copyright]
    name = "Möbius Group"

    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    url = "http://github.com/Mobius-Group"

[menu]
  # This displays buttons in the navbar to access your contents
  [[menu.main]]
    identifier = "about" # An unique identifier for the button
    name = "About"       # A display name for the button
    url = "/about/"      # The path to the content. It can lead to a single page (like here)
    weight = 10          # A number to order the buttons in the navbar

  [[menu.main]]
    identifier = "posts"
    name = "All posts"
    url = "/posts/"       # The path can lead to a content folder too.
    weight = 20

[taxonomies]
category = "categories"
tag = "tags"


[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true